[package]
name = "FlowerGarden"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

